/**
 * 30 个通用职业方向 —— 发给「其他人」做感性验证打分
 *
 * 与 `seed.ts`（个人定制清单）并列；偏普适职场路径，不绑定某一人的经历。
 *
 * 分类：
 *  A 专业深耕 (#1–#6)
 *  B 管理与业务一号位 (#7–#12)
 *  C 创业 / 自由职业 (#13–#18)
 *  D 内容与影响力 (#19–#23)
 *  E 切换与复合路径 (#24–#30)
 */

import type { QuickItem } from "./types";

export const OTHERS_PANEL_ID = "others-30";
export const OTHERS_PANEL_TITLE = "通用 · 30 个职业方向感性验证";

export const SEED_ITEMS_OTHERS: QuickItem[] = [
  {
    idx: 1,
    category: "A 专业深耕",
    title: "大厂 / 名企资深 IC（独立贡献者）",
    oneLiner: "在成熟组织里把一条技术或专业线做到极致，带小范围协作但不扛整盘 P&L。",
    dayInLife:
      "早上对齐跨组接口与评审；上午深度攻关一个难点；下午 mentor 新人或写设计文档；晚上偶尔 on-call 或收尾代码。",
    workContent: "架构 / 核心模块 / 质量与性能 / 技术规划 / 评审与传承。",
    workMethods: "OKR + 设计评审 + 文档文化；远程与办公室混合较常见。",
    evidence: [{ label: "麦肯锡《2026 全球人才趋势》：企业更愿为「稀缺专业深度」付溢价，IC 轨与 M 轨并行。" }],
  },
  {
    idx: 2,
    category: "A 专业深耕",
    title: "垂直领域解决方案架构师",
    oneLiner: "在金融、制造、医疗等强监管行业，把产品能力翻译成可落地方案与招投标材料。",
    dayInLife: "上午客户现状调研会；下午画架构蓝图与 PoC 排期；晚上改标书或合规问答。",
    workContent: "售前方案 / PoC / 投标支持 / 交付边界谈判 / 客户成功衔接。",
    workMethods: "项目制 + 高频客户现场 + 与销售、交付三角协作。",
    evidence: [{ label: "Gartner 企业软件支出预测：行业云与垂直方案增速持续高于通用 SaaS。" }],
  },
  {
    idx: 3,
    category: "A 专业深耕",
    title: "数据 / 算法科学家（业务嵌入型）",
    oneLiner: "长在业务团队里的量化角色：预测、实验、因果、增长模型，直接服务营收或成本。",
    dayInLife: "早上跑实验看板；中午和业务争指标定义；下午写 SQL / notebook；晚上跟工程对接上线。",
    workContent: "指标体系 / AB 实验 / 预测模型 / 数据叙事 / 埋点治理。",
    workMethods: "敏捷迭代 + 实验文化 + 与 PM、运营同桌办公。",
    evidence: [{ label: "哈佛商业评论中文《数据驱动决策》：嵌入业务的数据岗留存与影响力显著高于纯中台。" }],
  },
  {
    idx: 4,
    category: "A 专业深耕",
    title: "产品经理（B 端复杂系统）",
    oneLiner: "做多角色、长链路、权限与流程极重的 B 端产品，平衡客户定制与产品化。",
    dayInLife: "早上看工单与客户反馈；上午需求评审；下午画流程与写 PRD；晚上陪售前见客户。",
    workContent: "需求取舍 / 路线图 / 交互与信息架构 / 交付节奏 / 客户预期管理。",
    workMethods: "双周发版 + 客户共创 + RICE 或等价优先级框架。",
    evidence: [{ label: "IDC 中国企服报告：B 端 PM 缺口大、岗位对行业理解要求逐年提高。" }],
  },
  {
    idx: 5,
    category: "A 专业深耕",
    title: "财务 / 战略 FP&A",
    oneLiner: "在业务侧做预算、预测、经营分析，把数字翻译成管理层能决策的故事。",
    dayInLife: "上午关账或滚动预测；下午业务条线复盘会；晚上建模型调假设。",
    workContent: "预算 / 预测 / 单元经济 / 投资项目评估 / 董事会材料。",
    workMethods: "月度经营节奏 + 强 Excel / BI + 与业务一号位信任关系。",
    evidence: [{ label: "德勤《首席财务官展望》：FP&A 与战略融合是头部公司标配。" }],
  },
  {
    idx: 6,
    category: "A 专业深耕",
    title: "法务 / 合规（商事为主）",
    oneLiner: "处理合同、投融资条款、知识产权与监管应对，在商业扩张期控风险。",
    dayInLife: "早上审合同队列；中午业务需求会；下午改交易文件或对接外部律所；晚上处理突发函件。",
    workContent: "合同谈判 / 合规制度 / 争议管理 / 培训业务团队。",
    workMethods: "台账 + SLA + 与业务「可预期」的协作节奏。",
    evidence: [{ label: "汤森路透《企业法务压力指数》：跨境与数据合规 workload 持续上升。" }],
  },
  {
    idx: 7,
    category: "B 管理与业务一号位",
    title: "事业部 / 区域总经理",
    oneLiner: "对一块区域或产品线 P&L 负责，搭班子、定策略、扛增长与利润。",
    dayInLife: "早上看经营数字；上午核心客户拜访；下午内部组织与资源协调会；晚上应酬或跨区电话。",
    workContent: "战略取舍 / 销售与市场 / 供应链或交付 / 人才梯队 / 预算。",
    workMethods: "周经营会 + 强 KPI + 高频一线走动。",
    evidence: [{ label: "贝恩《中国增长报告》：区域型增长负责人仍是扩张期企业核心岗位。" }],
  },
  {
    idx: 8,
    category: "B 管理与业务一号位",
    title: "研发总监 / 工程 VP（百人内）",
    oneLiner: "管多条产品线或平台团队，在交付压力与技术债之间走钢丝。",
    dayInLife: "早上站会与风险清单；上午架构评审；下午招聘与 1:1；晚上处理线上事故复盘。",
    workContent: "技术路线图 / 组织设计 / 质量与效能 / 招聘 / 跨部门博弈。",
    workMethods: "双轨制交付 + tech debt 预算 + 工程文化塑造。",
    evidence: [{ label: "Stack Overflow Developer Survey：工程管理者最大挑战是「优先级与人员保留」。" }],
  },
  {
    idx: 9,
    category: "B 管理与业务一号位",
    title: "销售总监 / 大客负责人",
    oneLiner: "带团队拿单，自己也可能啃最大几个 account，直接决定现金流。",
    dayInLife: "早上 pipeline 会；下午客户高层会议；晚上投标或商务条款拉锯。",
    workContent: "客户分层 / 定价与折扣 / 渠道激励 / 预测准确性 / 关键人关系。",
    workMethods: "CRM 纪律 + 周复盘 + 强结果导向文化。",
    evidence: [{ label: "Salesforce《销售状态报告》：大客户周期拉长，对负责人综合素养要求更高。" }],
  },
  {
    idx: 10,
    category: "B 管理与业务一号位",
    title: "市场增长负责人（含投放与品牌）",
    oneLiner: "对获客成本与品牌心智同时负责，在效果与长期之间分配预算。",
    dayInLife: "早上看投放 ROI；中午创意与内容会；下午渠道合作谈判；晚上盯大促或直播数据。",
    workContent: "投放 / 内容营销 / 品牌战役 / 增长实验 / 预算分配。",
    workMethods: "增长飞轮 + 创意测试 + 与产品、销售数据对齐。",
    evidence: [{ label: "群邑《2026 媒介趋势》：效果广告与品牌建设的再平衡成为 CMO 议题。" }],
  },
  {
    idx: 11,
    category: "B 管理与业务一号位",
    title: "供应链 / 运营副总裁",
    oneLiner: "管采购、计划、物流、产能，在成本、时效与韧性三角里做决策。",
    dayInLife: "早上看 OTIF 与库存；上午工厂或仓巡线；下午 S&OP 会议；晚上处理断供或索赔。",
    workContent: "网络设计 / 供应商管理 / 数字化排产 / 成本节降 / 危机响应。",
    workMethods: "S&OP + 精益 + 风险预案；制造业与电商场景差异大。",
    evidence: [{ label: "麦肯锡供应链调研：地缘与气候风险使「韧性运营」岗位权重上升。" }],
  },
  {
    idx: 12,
    category: "B 管理与业务一号位",
    title: "人力一号位（HRD / CHRO 路径）",
    oneLiner: "搭组织、定薪酬绩效、管文化冲突，在融资或并购期压力最大。",
    dayInLife: "早上处理员工关系个案；上午管理层梯队会；下午薪酬方案与猎头对接；晚上改制度或全员信。",
    workContent: "组织设计 / 招聘与保留 / 绩效与激励 / 文化 / 合规用工。",
    workMethods: "业务伙伴模型 + 数据化人力分析 + 高管教练式沟通。",
    evidence: [{ label: "领英《2026 职场趋势》：HR 战略席位在中小企业快速上升。" }],
  },
  {
    idx: 13,
    category: "C 创业 / 自由职业",
    title: "独立技术顾问 / 架构外包",
    oneLiner: "按项目为多家公司提供架构评审、性能优化或上云迁移，时间自己切。",
    dayInLife: "上午客户视频会议；下午写评估报告；晚上学习新栈或维护个人品牌。",
    workContent: "技术尽调 / 改造方案 / 短期驻场 / 培训客户团队。",
    workMethods: "合同里程碑计费 + 口碑转介绍 + 控制并行项目数。",
    evidence: [{ label: "Upwork / Malt 类平台报告：资深工程顾问时薪溢价明显。" }],
  },
  {
    idx: 14,
    category: "C 创业 / 自由职业",
    title: "小型工作室创始人（设计 / 品牌 / 开发）",
    oneLiner: "3–15 人，接企业品牌、小程序、官网等，在创意与回款之间找平衡。",
    dayInLife: "早上审稿；上午客户提案；下午排期与救火；晚上商务或发票。",
    workContent: "客户获取 / 项目管理 / 核心出品把门 / 现金流。",
    workMethods: "定金 + 阶段验收 + 模板化交付降本。",
    evidence: [{ label: "Adobe《创意经济》：小型创意商业体在全球持续扩容。" }],
  },
  {
    idx: 15,
    category: "C 创业 / 自由职业",
    title: "垂直 SaaS 创始人",
    oneLiner: "选一个细分行业痛点做标准产品，冷启动靠行业人脉与标杆客户。",
    dayInLife: "早上看激活与续费；上午产品会；下午见客户或投资人；晚上写需求或公关章。",
    workContent: "PMF / 销售打法 / 融资 / 招聘 / 合规基线。",
    workMethods: "垂直社群 + 案例营销 + 年度合同驱动现金流。",
    evidence: [{ label: "Bessemer 云指数：垂直 SaaS 在部分赛道估值与增速脱钩于泛水平工具。" }],
  },
  {
    idx: 16,
    category: "C 创业 / 自由职业",
    title: "本地生活服务连锁（健身 / 美容 / 维修等）",
    oneLiner: "直营或加盟扩张，极度依赖选址、人效与复购。",
    dayInLife: "早上巡店；中午处理投诉与供应链；下午培训店长；晚上看各店坪效。",
    workContent: "门店模型 / 加盟政策 / 供应链 / 会员体系 / 本地投放。",
    workMethods: "SOP + 神秘客 + 强督导；区域密度策略。",
    evidence: [{ label: "艾瑞本地生活报告：到店业态连锁化率仍在提升。" }],
  },
  {
    idx: 17,
    category: "C 创业 / 自由职业",
    title: "跨境电商独立站创始人",
    oneLiner: "自有站 + 社媒引流，自己控品牌与毛利，但流量与合规波动大。",
    dayInLife: "早上看广告账户；上午选品或供应商视频；下午客服与物流异常；晚上研究新市场合规。",
    workContent: "选品 / DTC 站运营 / 投放 / 海外仓 / 客服与退换。",
    workMethods: "小步测款 + UGC + 邮件私域；平台政策风险需对冲。",
    evidence: [{ label: "eMarketer 跨境电商预测：独立站占比在部分品类稳步上升。" }],
  },
  {
    idx: 18,
    category: "C 创业 / 自由职业",
    title: "社会企业 / 公益机构负责人",
    oneLiner: "使命驱动，同时要对捐赠方、政府项目或影响力投资交代成果。",
    dayInLife: "上午项目点走访；下午写资助方报告；晚上志愿者培训或筹款活动筹备。",
    workContent: "项目设计 / 筹款 / 政府关系 / 团队激励（薪酬天花板低）。",
    workMethods: "逻辑框架 + 透明披露 + 多方利益相关者治理。",
    evidence: [{ label: "中国公益行业人才报告：负责人「商业+公益」双能力需求上升。" }],
  },
  {
    idx: 19,
    category: "D 内容与影响力",
    title: "行业垂直自媒体（图文 + 短视频）",
    oneLiner: "深耕一个赛道做解读与案例，靠广告、咨询线索或课程变现。",
    dayInLife: "早上刷行业动态；中午写稿或录口播；下午商务；晚上看粉丝互动数据。",
    workContent: "选题 / 内容生产 / 社群 / 商业合作谈判。",
    workMethods: "日更或周更节奏 + 平台算法适配 + 人设一致。",
    evidence: [{ label: "QuestMobile：垂直领域 KOL 广告单价仍高于泛娱乐。" }],
  },
  {
    idx: 20,
    category: "D 内容与影响力",
    title: "企业内训师 / 公开课讲师",
    oneLiner: "把方法论做成可复制的课，面对职场大课或企业大学学员。",
    dayInLife: "上午磨课与案例更新；下午交付；晚上收集反馈改大纲。",
    workContent: "课程设计 / 现场控场 / 课后作业与测评 / 复购线索。",
    workMethods: "模块化大纲 + 故事化案例 + 与 HR 采购周期对齐。",
    evidence: [{ label: "培训杂志《企业学习预算》：混合式学习预算占比继续提高。" }],
  },
  {
    idx: 21,
    category: "D 内容与影响力",
    title: "播客 /  newsletter 主理人",
    oneLiner: "长对话或深度写作积累信任，再衍生社群、活动或赞助。",
    dayInLife: "早上研究嘉宾背景；中午录音或写作；后期剪辑与排版占大量时间。",
    workContent: "嘉宾邀约 / 叙事剪辑 / 订阅增长 / 赞助与周边。",
    workMethods: "稳定更新频率 + 高质量 shownotes + 私域导流。",
    evidence: [{ label: "爱迪生研究《播客消费者》：中文播客商业赞助仍在早期红利。" }],
  },
  {
    idx: 22,
    category: "D 内容与影响力",
    title: "社区运营负责人（线上产品内社区）",
    oneLiner: "用话题、活动与 KOC 让用户留下来，指标是活跃、留存与 UGC。",
    dayInLife: "早上看社区数据；上午策划活动；下午处理争议内容；晚上陪核心用户。",
    workContent: "规则与风控 / 活动 / KOC 关系 / 与产品增长协同。",
    workMethods: "分层运营 + 情绪劳动高 + A/B 活动复盘。",
    evidence: [{ label: "Discord / Circle 类社区经济报告：品牌自建社区投入增加。" }],
  },
  {
    idx: 23,
    category: "D 内容与影响力",
    title: "投资人关系（IR）或公共事务",
    oneLiner: "对资本市场或政府叙事，管理预期、披露节奏与舆情。",
    dayInLife: "上午准备业绩材料；下午分析师会议或监管沟通；晚上修订公告措辞。",
    workContent: "披露合规 / 路演 / 媒体关系 / 危机公关预案。",
    workMethods: "严格日历 + 跨部门事实核对 + 高层话术统一。",
    evidence: [{ label: "港交所 / 上交所 IR 指引更新：ESG 叙事权重持续加大。" }],
  },
  {
    idx: 24,
    category: "E 切换与复合路径",
    title: "国企 / 事业单位稳定岗（职能或技术）",
    oneLiner: "流程规范、波动小，晋升与创新空间相对受限但安全感高。",
    dayInLife: "按固定节奏开会、写材料、走审批；突击检查或专项时加班明显。",
    workContent: "流程合规 / 材料撰写 / 横向协调 / 偶尔对外合作。",
    workMethods: "强流程 + 层级汇报 + 年度考核周期驱动。",
    evidence: [{ label: "智联招聘《稳就业偏好调研》：求稳人群比例在周期波动期上升。" }],
  },
  {
    idx: 25,
    category: "E 切换与复合路径",
    title: "外企中国区职能岗（市场 / 法务 / HR）",
    oneLiner: "全球总部政策与本地执行之间的翻译者与缓冲带。",
    dayInLife: "深夜跨洋会 + 白天对齐本地业务；合规邮件与英文材料占比高。",
    workContent: "全球项目落地 / 本地法规适配 / 跨文化沟通。",
    workMethods: "矩阵组织 + 强书面留痕 + 英文工作能力。",
    evidence: [{ label: "中国欧盟商会报告：外企在华职能岗编制趋紧、角色更复合。" }],
  },
  {
    idx: 26,
    category: "E 切换与复合路径",
    title: "公务员 / 选调路径",
    oneLiner: "公共服务与政策执行一线，稳定性极强，个人风格发挥空间相对小。",
    dayInLife: "按科室节奏处理群众事务或材料；专项期间连续值班。",
    workContent: "政策执行 / 材料 / 现场 / 多部门协调。",
    workMethods: "规范第一 + 程序正义 + 长期服务年限积累。",
    evidence: [{ label: "国家公务员局招录数据：热门岗位竞争比仍处高位。" }],
  },
  {
    idx: 27,
    category: "E 切换与复合路径",
    title: "高校教职 / 科研院所研究员",
    oneLiner: "论文、课题、带学生；非升即走压力下「自由」与「考核」并存。",
    dayInLife: "上午上课或组会；下午实验或写作；晚上审稿与改本子。",
    workContent: "科研产出 / 教学 / 课题申报 / 学术服务。",
    workMethods: "长周期项目 + 同行评议 + 学术网络。",
    evidence: [{ label: "Nature 职业版：全球青年研究者对编制与经费焦虑上升。" }],
  },
  {
    idx: 28,
    category: "E 切换与复合路径",
    title: "移民后的「降维重启」（蓝领技能 / 本地服务业）",
    oneLiner: "为身份与现金流先进入本地技工、物流、护理等赛道，再图二次跃迁。",
    dayInLife: "体力或轮班为主；语言与生活系统从零搭建；业余时间学认证或转行课。",
    workContent: "持证上岗 / 工时管理 / 家庭分工再谈判。",
    workMethods: "工会或社区资源 + 政府培训补贴 + 渐进式资格路径。",
    evidence: [{ label: "OECD 移民就业报告：首份工作与母语国职业匹配度普遍偏低。" }],
  },
  {
    idx: 29,
    category: "E 切换与复合路径",
    title: "半退休 + 非执行董事 / 顾问委员会",
    oneLiner: "减少全职强度，用经验换董事津贴或战略顾问费，选 board 质量很关键。",
    dayInLife: "月会季会为主；突发危机时被电话；其余时间自主安排。",
    workContent: "战略质询 / 引荐资源 / 风控提醒 / 高管教练。",
    workMethods: "声誉背书 + 边界清晰 + 多席位分散风险。",
    evidence: [{ label: "哈佛公司治理项目：独立董事时间与责任预期仍在上升。" }],
  },
  {
    idx: 30,
    category: "E 切换与复合路径",
    title: "「主业 + 副业」双轨（如白天上班 + 夜间独立项目）",
    oneLiner: "主业保现金流与社保，副业试 PMF 或兴趣变现，身体与合同条款是瓶颈。",
    dayInLife: "工作日晚上与周末几乎全部占满；长期需处理倦怠与合规（竞业）。",
    workContent: "时间块管理 / 副业产品或内容 / 税务与合同 / 是否转全职的决策点。",
    workMethods: "番茄或时间块 + MVP 验证 + 与雇主边界书面厘清。",
    evidence: [{ label: "盖洛普《全球职场状态》：多份收入源成为部分地区的常态 coping 策略。" }],
  },
];
