/**
 * 30 个职业机会的种子数据 —— Xue Nian 的感性验证打分清单
 *
 * 来源：用户基于 Step 1 价值观 + PrinciplesYou 信号 Step 2 发散出的 30 项。
 * 直接硬编码：本页面不调 LLM、不依赖前置 Step。
 *
 * 分类：
 *  A 教育主线（#1–#8）
 *  B 跨行业 · 组织+0-1（#9–#15）
 *  C 内容 / IP（#16–#20）
 *  D 投资 / 顾问 / 战略（#21–#25）
 *  E 组合 / 平台（#26–#30）
 */

import type { QuickItem } from "./types";

export const QUICK_PANEL_ID = "xuenian-30";
export const QUICK_PANEL_TITLE = "Xue Nian · 30 个职业机会感性验证";

export const SEED_ITEMS: QuickItem[] = [
  {
    idx: 1,
    category: "A 教育主线",
    title: "出海少儿启蒙教育创始人（东南亚 / 中东）",
    oneLiner: "把中国少儿启蒙的产品 + 教研 + 渠道复用到东南亚 / 中东市场，做品牌或平台。",
    dayInLife:
      "早 9 点跨时差对接迪拜 / 吉隆坡代理；上午把本地化教研版本和团队过一遍；下午跟潜在 LP / 产业资本月会；晚上拉本地家长私域数据；夜里签合规和合同邮件。",
    workContent: "本地化课程教研 / 代理与分销网络 / 本地化获客模型 / 融资与 LP 关系 / 跨国团队搭建。",
    workMethods: "远程为主 + 季度出差；OKR + 周战报；TikTok Shop / WhatsApp / 本地化数据看板。",
    evidence: [
      { label: "网易《2026-2027 全球母婴市场及中国母婴产业出海机遇报告》：全球母婴 2030 年 3084 亿美元，CAGR 7.5%；亚太占 40%+。" },
      { label: "巨人天成《母婴跨境 2026》：东南亚 / 中东人口红利显著，YOBOO 等品牌 TikTok Shop 直播销售占比 88%。" },
    ],
  },
  {
    idx: 2,
    category: "A 教育主线",
    title: "AI 学伴产品创始人（K12 智能体）",
    oneLiner: "做面向 K12 的 AI 学习智能体（学伴 / 教辅）+ to B 学校 / 连锁机构渠道。",
    dayInLife:
      "早上看 AI 模型评估指标和用户对话日志；午会跟教研负责人对内容；下午跟某市教育局 / 连锁机构谈 BD；晚上跟投资人 1:1。",
    workContent: "产品定义 / 教研内容设计 / 模型迭代决策 / B 端拓客 / 融资。",
    workMethods: "双轨制（模型 + 教研）；快速 MVP；与产业资本紧密互动。",
    evidence: [
      { label: "The Insight Partners：全球 K-12 AI 教育 2024 → 2031 由 3.91 亿美元升至 78.15 亿美元，CAGR 39.6%。" },
      { label: "36 氪《2026 巨头大战 AI 教育》：AI 教育月活破 1.2 亿、同比 +340%；B 端助教是当下唯一跑通盈利逻辑的路径。" },
    ],
  },
  {
    idx: 3,
    category: "A 教育主线",
    title: "成人 AI 工具教育自媒体 IP（B 站 / 小红书 / 视频号）",
    oneLiner: "教中产白领 / 35+ 职场人怎么用 AI 工具替代繁琐工作，靠付费课 / 训练营 / 智能体变现。",
    dayInLife:
      "早上扒 OpenAI / 字节 / 阿里 等新发布；上午做选题脚本；中午录 1 期短视频；下午社群运营 + 1v1；晚上看数据 + 跟剪辑对接。",
    workContent: "选题策划 / 录播 / 私域社群 / 训练营运营 / IP 商单。",
    workMethods: "脚本 + 录播 + 飞书私域 + 智能体；以「AI × 中年再造」为标签。",
    evidence: [
      { label: "虎嗅《2026 年搞个人 IP，如果还在想卖课，大概率是死路一条》：把专业经验封装为垂直智能体，而非传统课。" },
      { label: "凸知《2026 知识付费分水岭》：从公域租赁经济转向私域资产经济，企微社群成主流。" },
    ],
  },
  {
    idx: 4,
    category: "A 教育主线",
    title: "银发学习平台一号位",
    oneLiner: "针对 50+ 退休 / 准退休人群做兴趣 / 健康 / 生活类线上学习平台。",
    dayInLife: "早上听销售汇报；中午跟内容负责人选题；下午开供应商会；晚上看用户回访数据。",
    workContent: "课程内容采购 / 主播达人合作 / 直播私域成交 / 用户运营。",
    workMethods: "电话销售 + 微信社群 + 抖音直播；高情绪劳动 + 慢周期。",
    evidence: [
      { label: "中研普华《2026 AI 教辅及银发教育》：渗透率低、政策预期支持；但消费力 + 数字化能力双低。" },
    ],
  },
  {
    idx: 5,
    category: "A 教育主线",
    title: "新型 AI 职业教育平台 0–1 操盘手（AI 编程 / 跨境电商 / 数字化运营方向）",
    oneLiner: "0–1 操盘一个针对 90/95 后职场人的 AI 实操类职业教育平台，线上 + 线下混合。",
    dayInLife:
      "早上看招生漏斗；上午跟课程开发讨论 AI 全栈课程；午会拉销售；下午外勤拜访 1 家产业资本；晚上写 OKR 复盘。",
    workContent: "招生模型 / 课程产品 / 师资建设 / 渠道结构 / 政府关系。",
    workMethods: "中台化 + 渠道结构（她最强的方法论） + 直播投流 + 产教融合。",
    evidence: [
      { label: "中研普华《2026 中国 AI+职业教育》：市场规模将突破千亿；IT 职业教育 2025 已破 1200 亿。" },
      { label: "AtomGit AI 社区：AI 相关 IT 岗位招聘量同比 +128%；初级开发岗位 −35%；课程升级到 AI+ 全栈。" },
    ],
  },
  {
    idx: 6,
    category: "A 教育主线",
    title: "少儿教育连锁加盟操盘手（STEAM / 美育中心）",
    oneLiner: "在三四线扩张的少儿 STEAM / 美育连锁品牌做 COO 或区域负责人。",
    dayInLife: "早上看新店爬坡；午会跟督导 + 财务对账；下午开加盟商月会；晚上飞机出差到下个城市。",
    workContent: "店面爬坡 / 加盟商培训 / 选址 / 督导体系。",
    workMethods: "线下督导 + 加盟商 SOP + 标准化运营。",
    evidence: [{ label: "艾瑞 GenAI+教育报告：2025 教育信息化 5515 亿；线下小业态承压。" }],
  },
  {
    idx: 7,
    category: "A 教育主线",
    title: "私董会 / 高净值学习社群运营者",
    oneLiner: "面向高净值家长 / 创业者做付费学习社群 + 线下闭门会 + 私董。",
    dayInLife: "早上飞跨城；上午私董会主持；下午一对一咨询；晚上私域社群答疑。",
    workContent: "选人 / 选题 / 私董主持 / 线下闭门会组织。",
    workMethods: "极重社交 + 主持 / 引导能力。",
    evidence: [{ label: "36 氪《知识付费四大天王 兴于 IP 困于 IP》：私董增长承压。" }],
  },
  {
    idx: 8,
    category: "A 教育主线",
    title: "教育投资人（少儿 / AI 教育赛道 VC）",
    oneLiner: "在头部 VC 或产业资本里做教育赛道投资人，看少儿 / AI 教育早期项目。",
    dayInLife: "早上看 BP；上午跟创始人聊 1 小时；中午午会过 pipeline；下午尽调；晚上社交饭局。",
    workContent: "看项目 / 尽调 / 投后管理。",
    workMethods: "强人脉 + 强分析 + 强 social。",
    evidence: [{ label: "36 氪《2025 教育投资钱流向》：天使轮 62.5%；钱往志愿填报 / 留学申请等外围标准化环节。" }],
  },
  {
    idx: 9,
    category: "B 跨行业",
    title: "跨境电商品牌操盘手（女性 / 母婴消费品出海）",
    oneLiner: "在中型跨境电商品牌做 COO，操盘东南亚 / 中东 / 北美的母婴或女性消费品。",
    dayInLife: "早上看 TikTok Shop GMV；上午跟选品 / 投流团队会议；下午跟海外仓负责人远程；晚上看跨境直播复盘。",
    workContent: "选品 / 投流 / 海外仓 / 本地化达人 / 私域。",
    workMethods: "数据驱动 + 直播带货 + 全托管平台。",
    evidence: [
      { label: "巨人天成 母婴跨境 2026：YOBOO 在东南亚 TikTok Shop 直播占比 88%。" },
      { label: "网易报告：2024 H1 跨境母婴零售 81 亿、行业 Top3。" },
    ],
  },
  {
    idx: 10,
    category: "B 跨行业",
    title: "新消费连锁餐饮 / 咖啡品牌联创",
    oneLiner: "加入或合伙一个新兴餐饮 / 咖啡品牌做联合创始人 / 操盘手。",
    dayInLife: "早上巡店；中午跟产品研发对菜单；下午开门店爬坡周会；晚上吃同行家。",
    workContent: "门店模型 / 加盟管理 / 选址 / 供应链。",
    workMethods: "线下重运营 + 周报系统 + 口碑驱动。",
    evidence: [{ label: "艾媒 / 中研普华 2026 新消费报告系列。" }],
  },
  {
    idx: 11,
    category: "B 跨行业",
    title: "中国小众美妆 / 护肤新品牌创始人",
    oneLiner: "0–1 做一个差异化美妆 / 护肤品牌（功效护肤 / 香氛 / 银发护肤）。",
    dayInLife: "早上看 OEM 排产；上午跟成分研究员开会；下午抖音 / 小红书内容会；晚上看种草数据。",
    workContent: "产品研发 / OEM 管理 / 种草内容 / 私域复购。",
    workMethods: "供应链 + 内容种草 + 直播。",
    evidence: [{ label: "艾媒 / 36 氪 新消费品牌报告。" }],
  },
  {
    idx: 12,
    category: "B 跨行业",
    title: "SaaS 公司 COO（教育 SaaS / 行业 SaaS）",
    oneLiner: "在 B 端 SaaS 公司任 COO，做规模化运营 + 客户成功 + 渠道结构。",
    dayInLife: "早上看 CS 漏斗；午会跟销售对单；下午跟产品对路线图；晚上跟 CEO 月度复盘。",
    workContent: "销售运营 / 客户成功 / 渠道结构 / 组织治理。",
    workMethods: "数据驱动 + 季度 OKR + 客户分层运营。",
    evidence: [
      { label: "钛媒体《站在 2026 年看今天的 SaaS》：边际成本非线性 + 标准化 + 高粘性。" },
      { label: "教育 SaaS 报告：智慧教学 286 亿、CAGR 12%+。" },
    ],
  },
  {
    idx: 13,
    category: "B 跨行业",
    title: "MCN 公司联合创始人（垂直 IP 矩阵）",
    oneLiner: "和达人 / 内容操盘手共同创业，做某细分赛道的 IP 矩阵 MCN。",
    dayInLife: "早上看达人涨粉数据；上午跟达人 1v1；下午跟商务对单；晚上拍片场。",
    workContent: "签约 / 培育 / 投流 / 商单 / 矩阵搭建。",
    workMethods: "内容生产线 + 投流模型 + 商单经纪。",
    evidence: [{ label: "人人文库《2026 中国 MCN 行业研究报告》：微利承压、AIGC 赋能、出海拓展。" }],
  },
  {
    idx: 14,
    category: "B 跨行业",
    title: "AI 应用层创业（教育 / 内容 / B 端工具）",
    oneLiner: "0–1 一家 AI 应用层公司，可能落在 K12、成人教育、B 端营销、HR 等场景。",
    dayInLife: "早上跟 CTO 看模型表现；午会跟产品 + 销售对客户案例；下午跟潜在客户合谈；晚上写月度信。",
    workContent: "场景定义 / 模型选型 / GTM / 融资。",
    workMethods: "MVP + 客户共创 + 产业资本绑定。",
    evidence: [
      { label: "腾讯新闻《AI+教育新业态 2026-03》：垂直数据资产 + 教研深度 = 核心壁垒。" },
      { label: "36 氪《2025 教育投资钱流向》：天使轮 62.5%、产业资本占主导。" },
    ],
  },
  {
    idx: 15,
    category: "B 跨行业",
    title: "城市连锁体验空间（亲子 / 女性 / 银发）",
    oneLiner: "在一二线城市做体验型线下空间品牌（如亲子探索馆、女性疗愈空间）。",
    dayInLife: "早上巡场；中午看预约系统；下午做活动策划会；晚上盘账。",
    workContent: "选址 / 运营 / 活动策划 / 会员体系。",
    workMethods: "线下重资产 + 会员制。",
    evidence: [{ label: "艾媒 / 36 氪 新消费空间案例。" }],
  },
  {
    idx: 16,
    category: "C 内容 / IP",
    title: "教育创业者深度访谈 IP",
    oneLiner: "做教育创业者深度访谈视频 / 播客（视频号 + 小宇宙）。",
    dayInLife: "早上准备访谈大纲；中午赴约访谈；下午剪辑会议；晚上写下期主题。",
    workContent: "访谈内容 / 嘉宾邀约 / 后期剪辑。",
    workMethods: "深度访谈 + 长视频 + 公众号长文。",
    evidence: [{ label: "晚点 / 虎嗅 / 36 氪 创业者访谈节目案例。" }],
  },
  {
    idx: 17,
    category: "C 内容 / IP",
    title: "知识付费 IP（管理 / 创业课程作者）",
    oneLiner: "把过往中台 / 渠道结构 / 0-1 经验做成体系化课 + 训练营。",
    dayInLife: "早上写课程大纲；中午对接训练营班主任；下午做新课程市场调研；晚上做用户访谈。",
    workContent: "课程内容 / 训练营运营 / 私域转化。",
    workMethods: "录播 + 训练营 + 私域。",
    evidence: [{ label: "虎嗅《2026 卖课死路》、36 氪《知识付费四大天王 困于 IP》。" }],
  },
  {
    idx: 18,
    category: "C 内容 / IP",
    title: "高管 / 业务一号位认知专栏 + 付费社群",
    oneLiner: "用「业务一号位」第一视角做认知专栏，配套高净值私域社群。",
    dayInLife: "早上写认知卡片；中午社群答疑；下午约 2 个创始人深聊（积累素材）；晚上跟编辑 / 助理对节奏。",
    workContent: "公众号 / 小红书 / 视频号长内容 + 付费社群运营。",
    workMethods: "深度长文 + 高客单付费社群 + 周直播。",
    evidence: [
      { label: "凸知《2026 知识付费私域分水岭》：私域成主流。" },
      { label: "虎嗅《2026 卖课死路》：把经验封装为智能体 = 新护城河。" },
    ],
  },
  {
    idx: 19,
    category: "C 内容 / IP",
    title: "财经 / 商业类短视频 IP（女性视角）",
    oneLiner: "做财经 / 商业类短视频 IP，主打「女性高管商业分析」差异化。",
    dayInLife: "早上扒新闻；上午写脚本；中午录制；下午剪辑反馈；晚上看选题数据。",
    workContent: "选题 / 脚本 / 出镜 / 投流。",
    workMethods: "脚本短视频 + 头条投流 + 直播。",
    evidence: [{ label: "36 氪 / 媒训《MCN 网红规模化创作》。" }],
  },
  {
    idx: 20,
    category: "C 内容 / IP",
    title: "视频号直播带货操盘手（教育 / 亲子品类）",
    oneLiner: "在视频号教育 / 亲子品类做主理人 + 主播 + 操盘手。",
    dayInLife: "早上看昨日 GMV；中午选品；下午开直播会；晚上 8–11 点直播。",
    workContent: "选品 / 直播执行 / 私域承接 / 投流。",
    workMethods: "长直播 + 投流模型 + 选品池。",
    evidence: [{ label: "人人文库《2026 MCN 报告》：电商 + MCN 边界模糊。" }],
  },
  {
    idx: 21,
    category: "D 投资 / 顾问 / 战略",
    title: "创业孵化器 / 加速器合伙人",
    oneLiner: "在创业孵化器做合伙人，对接早期教育 / AI 项目，和地方政府绑定。",
    dayInLife: "早上跨城出差；中午到孵化器跟创业者吃饭；下午对接政府对接 LP；晚上 demo day 复盘。",
    workContent: "招募 / 投后 / 政府关系 / LP 关系。",
    workMethods: "强社交 + 政府关系 + 长周期。",
    evidence: [{ label: "36 氪 创业孵化案例报道。" }],
  },
  {
    idx: 22,
    category: "D 投资 / 顾问 / 战略",
    title: "业务咨询合伙人 / 创始人陪跑型",
    oneLiner: "做创始人 / 业务一号位的「副驾驶」型咨询，按月 / 按里程碑收费。",
    dayInLife: "早上飞客户公司；上午开战略会；下午陪开经营会；晚上飞下个客户。",
    workContent: "战略陪跑 / 高管教练 / 业务诊断。",
    workMethods: "项目制 + 高频出差 + 1:1。",
    evidence: [{ label: "艾瑞 / 罗兰贝格 中国战略咨询案例。" }],
  },
  {
    idx: 23,
    category: "D 投资 / 顾问 / 战略",
    title: "战略投资业务负责人（产业资本）",
    oneLiner: "在大型产业集团（教育 / 互联网 / 消费）做战投负责人。",
    dayInLife: "早上看 BP；上午跟事业部对协同；下午跟潜在标的尽调；晚上跟集团 CFO 对账。",
    workContent: "项目筛选 / 尽调 / 协同议价 / 投后。",
    workMethods: "强分析 + 强合规 + 强协同。",
    evidence: [{ label: "36 氪《2025 教育投资钱流向》：产业资本与地方引导基金参与度提升。" }],
  },
  {
    idx: 24,
    category: "D 投资 / 顾问 / 战略",
    title: "早期 VC investment partner",
    oneLiner: "在头部 VC 任 partner / VP，看女性 / 教育 / 家庭赛道。",
    dayInLife: "早上看 BP；中午吃饭社交；下午尽调；晚上行业 mixer。",
    workContent: "看项目 / 尽调 / 出手 / 投后。",
    workMethods: "强社交 + 强分析。",
    evidence: [{ label: "36 氪 / 投中网 VC 行业报告。" }],
  },
  {
    idx: 25,
    category: "D 投资 / 顾问 / 战略",
    title: "业务诊断 / 接管型 CEO（连锁 / 服务业 turnaround）",
    oneLiner: "进入一家陷入困境的中型公司（连锁餐饮、服务业、教育）任 CEO 做 turnaround。",
    dayInLife:
      "早上听三个事业部各自 30 分钟；上午开经营分析会；中午约关键人 1:1；下午组织调整方案；晚上跟董事会同步进展。",
    workContent: "经营诊断 / 组织重塑 / 渠道结构 / 现金流救火 / 人事调整。",
    workMethods: "30/60/90 计划 + 强 KPI + 严格淘汰。",
    evidence: [
      { label: "她过往：核桃科学扭亏为盈 + 简小知渠道结构测试 + 火花武汉 0-1 = 标准 turnaround paper trail。" },
      { label: "36 氪 / 晚点 LatePost 中国中型公司 turnaround 案例报道（2024–2026）。" },
    ],
  },
  {
    idx: 26,
    category: "E 组合 / 平台",
    title: "个人 LP + 兼职顾问",
    oneLiner: "用过往收入做小额 LP 跟投 + 兼职做战略顾问，两条腿。",
    dayInLife: "早上看 1 个项目 BP；中午跟 1 个 GP 喝咖啡；下午做 1 家客户陪跑；晚上看孩子。",
    workContent: "看项目 + 顾问陪跑 + 个人投资。",
    workMethods: "轻协作 + 远程为主。",
    evidence: [{ label: "晚点 / 36 氪 个人 LP 案例。" }],
  },
  {
    idx: 27,
    category: "E 组合 / 平台",
    title: "家族办公室运营者",
    oneLiner: "为高净值家族 / 多家共同体做 MFO 运营。",
    dayInLife: "早上看资产配置；中午跟客户家族年轻一代；下午跟外部 GP 谈；晚上跟客户晚饭。",
    workContent: "资产配置 / 家族治理 / 子女教育 / 二代陪伴。",
    workMethods: "高情绪劳动 + 高隐私 + 长周期。",
    evidence: [{ label: "FT / 财新 中国家办报告。" }],
  },
  {
    idx: 28,
    category: "E 组合 / 平台",
    title: "跨界创新孵化空间运营",
    oneLiner: "做一个面向中型公司创新部门的孵化 / 联创空间。",
    dayInLife: "早上接洽客户；中午客户答辩；下午开方案会；晚上做项目复盘。",
    workContent: "招商 / 客户运营 / 项目孵化。",
    workMethods: "重运营 + 重社交。",
    evidence: [{ label: "36 氪 / 虎嗅 创新空间案例。" }],
  },
  {
    idx: 29,
    category: "E 组合 / 平台",
    title: "成人女性赋能社群品牌",
    oneLiner: "做面向 35+ 中产女性的成长 / 再就业社群品牌。",
    dayInLife: "早上做选题；中午社群直播；下午开 1v1；晚上跟同伴们晚饭。",
    workContent: "社群运营 / 内容 / 课程 / 训练营。",
    workMethods: "深度陪伴 + 高情绪劳动。",
    evidence: [{ label: "36 氪 / 虎嗅 女性社群案例。" }],
  },
  {
    idx: 30,
    category: "E 组合 / 平台",
    title: "新型 AI 职业教育平台 0–1（线上+线下）",
    oneLiner:
      "做面向求职 / 转型人群的 AI 实操类职业教育平台（如 AI 实操 / 数字化运营 / 跨境运营），混合线上+线下交付。",
    dayInLife: "早上招生数据；上午课程产品会；下午商务拓展；晚上学员社群直播。",
    workContent: "招生 / 课程 / 师资 / 渠道 / 政府关系。",
    workMethods: "中台化 + 渠道结构 + 直播投流。",
    evidence: [
      { label: "中研普华《2026 AI+职业教育》、CSDN AtomGit《2026 IT 职业教育冲击》。" },
    ],
  },
];
